tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "sheldon"
brew "yarn"

cask "discord"
cask "fig"
cask "figma"
cask "google-chrome"
cask "insomnia"
cask "notion"
cask "raycast"
cask "spotify"
cask "visual-studio-code"
cask "whatsapp"
