tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "stow"
brew "starship"

cask "discord"
cask "figma"
cask "google-chrome"
cask "insomnia"
cask "notion"
cask "spotify"
cask "visual-studio-code"
cask "whatsapp"
cask "cleanshot"
cask "bartender"