add_newline=false

format = """
$username\
$hostname\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$nodejs\
$sudo\
$line_break\
$jobs\
$status\
$shell\
$directory\
$character"""

[username]
show_always=true
format="[$user]($style) "

[nodejs]
symbol="⬢ "