# `sheldon` configuration file
shell = "zsh"

[plugins]

[plugins.spaceship]
github = "spaceship-prompt/spaceship-prompt"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.fast-syntax-highlighting]
github = "zdharma/fast-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-nvm]
github = "lukechilds/zsh-nvm"
apply = ["defer"]

[templates]
defer = { value = 'zsh-defer source "{{ file }}"', each = true }
