# `sheldon` configuration file
shell = "zsh"

[plugins]

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-nvm]
github = "lukechilds/zsh-nvm"
apply = ["defer"]

[templates]
defer = { value = 'zsh-defer source "{{ file }}"', each = true }
