# `sheldon` configuration file
shell = "zsh"

[plugins]

[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"

# theme
[plugins.dracula-pro]
local = "~/.dotfiles/dracula-pro/themes/zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-nvm]
github = "lukechilds/zsh-nvm"
apply = ["defer"]

[plugins.fast-syntax-highlighting]
github = "zdharma/fast-syntax-highlighting"
apply = ["defer"]

[templates]
defer = { value = 'zsh-defer source "{{ file }}"', each = true }
